<?php

/**
 * @file
 * Customization module for Presbyterian Historical Society.
 */

/**
* Implements hook_block_info().
*/
function presbydora_block_info() {
  $blocks = array();
  $blocks['presbydora_name'] = array(
    'info' => t('PHS Site Name'),
  );
  $blocks['presbydora_donate'] = array(
    'info' => t('PHS Site Donation Button'),
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function presbydora_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'presbydora_name':
      $block['subject'] = 'Presbyterian Historical Society site name';
      $block['content'] = variable_get('site_name', "");
      break;
      
    case 'presbydora_donate':
      $block['subject'] = 'Presbyterian Historical Society Donate Button';
      $block['content'] = theme_button(
        array(
          "title" => t("Donate"),
          "value" => t("Donate"),
        )
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function presbydora_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if (!empty($data['tabs'])) {
    $object = menu_get_object('islandora_object', '2');
    if ($object && isset($object['MODS']) && islandora_datastream_access(ISLANDORA_METADATA_EDIT, $object['MODS']))
      $data['tabs'][0]['output'][] = array(
        '#theme' => 'menu_local_task',
        '#link' => array(
          'title' => t('Edit MODS'),
          'href' => "islandora/object/{$object->id}/datastream/MODS/edit",
          'localized_options' => array(),
          'weight' => 99,
        ),
      );

    $data['tabs'][0]['count'] = $data['tabs'][0]['count'] + 1;

    foreach ($data['tabs'][0]['output'] as &$tab) {
      $tab['#weight'] = $tab['#link']['weight'];
    }
  }
}
