<?php

/**
 * @file
 * Customization module for Presbyterian Historical Society.
 */

 /**
  * Implements hook_menu().
  */
function presbydora_menu() {
  $items = array();

  $items['admin/islandora/presbydora'] = array(
    'title' => 'Presbydora Admin',
    'description' => 'Configuration to specify objects that can bypass datastream access check.',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('presbydora_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
  );

  $items['islandora/object/%islandora_object/view_text'] = array(
    'title' => 'Transcript',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'presbydora_text_view',
    'page arguments' => array(2),
    'access callback' => 'presbydora_access_text_view',
    'access arguments' => array(2),
    'file' => 'includes/utilities.inc',
  );

  return $items;
}

/**
 * Access callback.
 *
 * @param AbstractObject $object
 *   The object to test, if NULL the given object doesn't exist or is
 *   inaccessible.
 *
 * @return bool
 *   TRUE if the user is allowed to view the TEXT datastream (if present) and
 *   if the Object has the Oral Histories Content Model, FALSE otherwise.
 */
function presbydora_access_text_view(AbstractObject $object) {
  return is_object($object) && isset($object['TEXT']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $object['TEXT']) && in_array('islandora:oralhistoriesCModel', $object->models);
}

/**
 * Implements hook_block_info().
 */
function presbydora_block_info() {
  $blocks = array();
  $blocks['presbydora_name'] = array(
    'info' => t('PHS Site Name'),
  );
  $blocks['presbydora_donate'] = array(
    'info' => t('PHS Site Donation Button'),
  );
  $blocks['presbydora_metadata_description'] = array(
    'info' => t('Metadata Description'),
  );
  return $blocks;
}

/**
 * Implements hook_theme().
 */
function presbydora_theme($existing, $type, $theme, $path) {
  return array(
    'presbydora_metadata_description' => array(
      'template' => 'theme/presbydora-metadata-description',
      'variables' => array(
        'object' => NULL,
        'metadata' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function presbydora_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'presbydora_name':
      $block['subject'] = 'Presbyterian Historical Society site name';
      $block['content'] = variable_get('site_name', "");
      break;

    case 'presbydora_donate':
      $block['subject'] = 'Presbyterian Historical Society Donate Button';
      $block['content'] = theme_button(
        array(
          "title" => t("Donate"),
          "value" => t("Donate"),
        )
      );
      break;

    case 'presbydora_metadata_description':
      $object = menu_get_object('islandora_object', 2);
      $block['subject'] = t('Islandora Metadata Description');
      $block['content'] = array(
        '#theme' => 'presbydora_metadata_description',
        '#object' => $object,
      );
      break;

  }
  return $block;
}

/**
 * Implements hook template_preprocess_page().
 *
 * Default mobile users to list view on object and search pages.
 */
function presbydora_preprocess_page(&$vars) {
  if (module_exists('phs_context_feature')) {

    // Check if we are on an Islandora Object page, or an Islandora Search Page.
    $path_parts = explode("/", current_path());
    if ($path_parts[0] == 'islandora' &&
      ($path_parts[1] == 'object' ||
      $path_parts[1] == 'search')) {

      // Current supported contexts (mobile or tablet).
      $mobile_detection = function () {

        // Available contexts, configured in the Context UI Module.
        // context_active_contexts() returns an array of stdClass objects, with
        // Array keys required for name comparison.
        $contexts = array_keys(context_active_contexts());
        return array_intersect(
          array(
            'mobile_device_detect_context',
            'tablet_device_detect_context',
          ),
          $contexts
        );
      };

      // Only when the context tells us, default the user to 'List' view
      // When dealing with mobile or tablet devices.
      if ($mobile_detection()) {

        // Stop processing if we are already on grid view.
        // Default view is 'List'.
        $query_params = drupal_get_query_parameters();
        if (!isset($query_params['display'])) {
          $query_params['display'] = 'grid';
          drupal_goto(
            current_path(),
            array(
              'query' => $query_params,
            )
          );
        }
      }
    }
  }
}

/**
 * Process variables for vermontdora_metadata_description template.
 *
 * Default template: presbydora-metadata-description.tpl.php.
 *
 * @param array $variables
 *   An associative array containing:
 *   - object: The object for which we are being rendered.
 *   - metadata: Either a rendered metadata display or NULL. If NULL, we will
 *     go render it ourselves.
 */
function template_process_presbydora_metadata_description(&$variables) {
  module_load_include('inc', 'islandora', 'includes/metadata');
  if ($variables['metadata'] === NULL && $variables['object']) {
    $variables['metadata'] = islandora_solr_metadata_description_callback($variables['object']);
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function presbydora_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if (!empty($data['tabs'])) {
    $object = menu_get_object('islandora_object', '2');

    if ($object && isset($object['MODS']) && islandora_datastream_access(ISLANDORA_METADATA_EDIT, $object['MODS'])) {
      $data['tabs'][0]['output'][] = array(
        '#theme' => 'menu_local_task',
        '#link' => array(
          'title' => t('Edit MODS'),
          'href' => "islandora/object/{$object->id}/datastream/MODS/edit",
          'localized_options' => array(),
          'weight' => 96,
        ),
      );
    }

    $data['tabs'][0]['count'] = $data['tabs'][0]['count'] + 1;

    foreach ($data['tabs'][0]['output'] as &$tab) {
      if ($tab['#link']['title'] === 'Manage') {
        $tab['#link']['weight'] = 97;
      }
      if ($tab['#link']['title'] === 'IP Embargo') {
        $tab['#link']['weight'] = 98;
      }
      if ($tab['#link']['title'] === 'Print Object') {
        $tab['#link']['weight'] = 99;
      }
      $tab['#weight'] = $tab['#link']['weight'];
    }
  }
}

/**
 * Implements hook_process_islandora_solr_metadata_display().
 */
function presbydora_process_islandora_solr_metadata_display(array &$variables) {
  presbydora_remove_solr_metadata_fields($variables, 'solr_fields');
}

/**
 * Implements hook_process_islandora_solr_metadata_description().
 */
function presbydora_process_islandora_solr_metadata_description(array &$variables) {
  presbydora_remove_solr_metadata_fields($variables, 'description');
}

/**
 * Remove fields from Solr metadata based on datastream access.
 *
 * @param array $variables
 *   Theme variables.
 * @param string $key
 *   The key of the array to remove the fields form.
 */
function presbydora_remove_solr_metadata_fields(&$variables, $key) {
  $object = $variables['islandora_object'];
  $mapping = array(
    'OCR_t' => 'OCR',
    'text_nodes_HOCR_hlt' => 'HOCR',
  );
  foreach ($mapping as $field => $dsid) {
    if (isset($variables[$key][$field])) {
      if (isset($object[$dsid]) && !islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $object[$dsid])) {
        unset($variables[$key][$field]);
      }
    }
  }
}

/**
 * Implements hook_form_islandora_scholar_embargo_alter().
 */
function presbydora_form_islandora_scholar_embargo_form_alter(&$form, &$form_state, $form_id) {
  $form['embargo_date']['#after_build'] = array('presbydora_embargo_date_set_year_range');
}

/**
 * Implements hook_form_islandora_ip_embargo_object_embargo_form_alter().
 */
function presbydora_form_islandora_ip_embargo_object_embargo_form_alter(&$form, &$form_state, $form_id) {
  $form['expiry_date']['#after_build'] = array('presbydora_embargo_date_set_year_range');
}

/**
 * Override original year range.
 */
function presbydora_embargo_date_set_year_range($form_element, $form_values) {
  $year = date("Y");
  $form_element['year']['#options'] = drupal_map_assoc(range($year, $year + 500));
  return $form_element;
}

/**
 * Implements hook_islandora_object_access().
 */
function presbydora_islandora_datastream_access($op, $islandora_datastream, $user) {
  if ($islandora_datastream->id == 'OBJ' || $islandora_datastream->id == 'PDF') {
    // Modified to allow specific objects to be accessible.
    $object = $islandora_datastream->parent;
    $pid = $object->id;

    module_load_include('inc', 'presbydora', 'includes/utilities');
    $bypass_pids = variable_get('presbydora_access_bypass_pids', array());
    if (!empty($bypass_pids)) {
      $ancestors = presbydora_get_ancestors($pid);
      $is_intersect = !empty(array_intersect($ancestors, $bypass_pids));

      if ($is_intersect) {
        return NULL;
      }
    }
    $guest = user_role_load_by_name('PHS Guest');
    if ($user->uid == 0 || (isset($guest->rid) && user_has_role($guest->rid, $user))) {
      return FALSE;
    }
  }
}

/**
 * Implements hook_cmodel_pid_islandora_object_purged().
 */
function presbydora_islandora_collectioncmodel_islandora_object_purged($pid) {
  $bypass_pids = variable_get('presbydora_access_bypass_pids', array());
  if (!empty($bypass_pids)) {
    unset($bypass_pids[$pid]);
    variable_set('presbydora_access_bypass_pids', $bypass_pids);
  }
}
